services:
  ros-humble-turtlebot3:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USERNAME: "${USER}"
        USER_UID: "${UID}"
        USER_GID: "${GID}"
        USER_HOME_DIR: "${HOME}"
    container_name: ${USER}-ros-humble-turtlebot3
    network_mode: "host"
    environment:
      - TERM=xterm-256color
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=burger
    volumes:
      - ${HOME}:${HOME}
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
