# version: '3.9'

services:
  ros2_nav2:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USERNAME: "${USER}"
        USER_UID: "${UID}"
        USER_GID: "${GID}"
        USER_HOME_DIR: "${HOME}"
    container_name: ros2_turtlebot3
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
             - capabilities: [gpu]
               count: all
    environment:
      - TERM=xterm-256color
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # - XAUTHORITY=/root/.Xauthority
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ${HOME}:${HOME}
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - $XAUTHORITY:/root/.Xauthority
      - /mnt/wslg:/mnt/wslg
    stdin_open: true
    tty: true